// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Thermon.CompuTrace.UI.Automation.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UserProfileFeature : object, Xunit.IClassFixture<UserProfileFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "UserProfile.feature"
#line hidden
        
        public UserProfileFeature(UserProfileFeature.FixtureData fixtureData, Thermon_CompuTrace_UI_Automation_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "UserProfile", " Add Connection String and User Profile Validations ", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Add Connection")]
        [Xunit.TraitAttribute("FeatureTitle", "UserProfile")]
        [Xunit.TraitAttribute("Description", "Add Connection")]
        [Xunit.TraitAttribute("Category", "Test1,")]
        [Xunit.TraitAttribute("Category", "SmokeTest,")]
        [Xunit.TraitAttribute("Category", "RegressionTest")]
        public void AddConnection()
        {
            string[] tagsOfScenario = new string[] {
                    "Test1,",
                    "SmokeTest,",
                    "RegressionTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Connection", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 9
 testRunner.Given("I click User Profile button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table37 = new TechTalk.SpecFlow.Table(new string[] {
                            "connectionName",
                            "connectionString"});
                table37.AddRow(new string[] {
                            "Connect1",
                            "Data Source=devdata001.southcentralus.cloudapp.azure.com;Initial Catalog=CompuTra" +
                                "ce.ProdSnapshot;User Id=computrace;Password=DefaultSQLServerP@ssw0rd;Persist Sec" +
                                "urity Info=true;"});
                table37.AddRow(new string[] {
                            "Connect2",
                            "Data Source=devdata001.southcentralus.cloudapp.azure.com;Initial Catalog=CompuTra" +
                                "ce.ProdSnapshot;User Id=computrace;Password=DefaultSQLServerP@ssw0rd;Persist Sec" +
                                "urity Info=true;"});
#line 10
 testRunner.When("I click on Add connection button & enter the details and click on save button", ((string)(null)), table37, "When ");
#line hidden
#line 14
 testRunner.Then("I should see connection string added", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="User profile as a default user")]
        [Xunit.TraitAttribute("FeatureTitle", "UserProfile")]
        [Xunit.TraitAttribute("Description", "User profile as a default user")]
        [Xunit.TraitAttribute("Category", "Test2,")]
        [Xunit.TraitAttribute("Category", "SmokeTest,")]
        [Xunit.TraitAttribute("Category", "RegressionTest")]
        public void UserProfileAsADefaultUser()
        {
            string[] tagsOfScenario = new string[] {
                    "Test2,",
                    "SmokeTest,",
                    "RegressionTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User profile as a default user", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 21
 testRunner.Given("I click User Profile button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 22
 testRunner.When("I enter User Domain Name \'QA Automation\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 23
 testRunner.And("I click Update button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 24
 testRunner.Then("I should see success message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="User Profile as a different user")]
        [Xunit.TraitAttribute("FeatureTitle", "UserProfile")]
        [Xunit.TraitAttribute("Description", "User Profile as a different user")]
        [Xunit.TraitAttribute("Category", "Test3,")]
        [Xunit.TraitAttribute("Category", "SmokeTest,")]
        [Xunit.TraitAttribute("Category", "RegressionTest")]
        public void UserProfileAsADifferentUser()
        {
            string[] tagsOfScenario = new string[] {
                    "Test3,",
                    "SmokeTest,",
                    "RegressionTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Profile as a different user", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 30
 testRunner.Given("I click User Profile button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 31
 testRunner.When("I enter user name \'Thermon Client\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 32
 testRunner.And("I enter user email \'thermonclient@gmail.com\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 33
 testRunner.And("I enter User Domain Name \'Thermon\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 34
 testRunner.And("I click Update button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 35
 testRunner.Then("I should see success message", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                UserProfileFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                UserProfileFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
